### ISSUE TITLE
Decide on a `deleted` triple

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf-ldp#19]
We are currently marking resources as "deleted" (as a result of `DELETE` requests; and leading to `Gone` responses) by adding a triple `<> rdf:type owl:Nothing` to the resource's `#metagraph`. This is probably a bit ontologically heavy.

Perhaps a better approach is `<> ns:deleted true`, where `ns` is some internal namespace?  An initial search (and asking around) didn't turn up a general solution for this.

**Comment by no-reply** [comment]
Ping: @gkellogg. Any obvious solutions for this? Is the internal predicate with boolean value the best approach?

**Comment by gkellogg** [comment]
Don't think I really have the background to say. Is the idea that when you delete a resource in the default (target) graph,  you record the resource as being deleted in a metagraph? Do you also remember the statements previously involving that resource?

The PROV model probably has more to say about this, but I think as Dydra implemented, it involves keeping every previous state of the container read-only, and using a prov graph to thread them together; any change creates a new graph in the container with deltas from the previous graph. @lisp or @bendiken could say more about this.

Short of that, then using some statement involving the resource in a metagraph is certainly reasonable.

**Comment by lisp** [comment]
a marking approach sounds treacherous:
- what happens when one wants to re-create a  resource?
- what happens with the containment assertions?

**Comment by no-reply** [comment]
@gkellogg said:

> Is the idea that when you delete a resource in the default (target) graph, you record the resource as being deleted in a metagraph? 

Exactly. This allows us to prevent unintended URI reuse (per good practice & LDP), and mark resources Gone, rather that 404.

> Do you also remember the statements previously involving that resource?

Optionally. This allows for inspection of the "tombstone" and/or recovery mechanisms.

@lisp said:

> what happens when one wants to re-create a resource?

HTTP `Conflict`. Unless a server has specified some other behavior for resource recovery. LDP is opinionated about this (correctly, I think).

> what happens with the containment assertions?

They are cleaned up according to LDP's DELETE specs. I believe the current code base handles this fine. Any previous containment would be cleared out on DELETE, and recovery handling is up to a specific implementation. 

I don't really plan that Lamprey will handle 'undeletion', so the marking is really just a way to avoid forgetting that the resource existed to begin with.

To be clear: `#graph` may be empty (often, it will be) and still have the resource exist. All internal server properties (there aren't many) are handled within `#metagraph`.

**Comment by no-reply** [comment]
@gkellogg Good call on PROV. `prov:invalidatedAtTime` seems to work, here.

@lisp Can you say more about your concerns about marking? I would love to be warned off a mistake while it's still easy to change directions.

**Comment by no-reply** [comment]
Now destroying by setting an `invalidateAtTime`. Closed by 415d4c667c4.

**Comment by lisp** [comment]
i will try.

the ways to manage data of temporal nature - which this is, as soon as you want to make something "disappear", all involve distinguishing (at least) two aspects: "valid" and "transaction" state.
if you start here, https://en.wikipedia.org/wiki/Temporal_database, you can enjoy the benefits of thirty years of research literature.

a valid dimension concerns the interval(s) during which the "truth" of some assertion contributes to a reasoning process v/s when its contribution is that of not being true - whether that being "false" of being "unknown", depending on the modes permitted by the logic.
in this dimension there are unknowns, uncertainty, modalities and whatever.
the dimension is projective, that is it concerns the state of the thing modelled and can support discussions of topics such as whether charles olson was channeling tarski.

a transaction dimension, on the other hand, concerns intervals when something is known in a model.
it is introspective and concerns the state of the model, rather than the state of the thing modelled.
it reflects this state with a fairly definitive degree of certainty 
at least, i do not recall any literature which introduces questions of grounding or uncertainty into that dimension.

the principle distinction in the results of that research in the form of databases is, which dimensions are "first class". the tquel -> tsql -> sql3 v/s sql -> sql-2011 evolution manifests this distinction and demonstrated a preference for date's exposition over snodgrass', in that they decided to expose both dimensions as table columns. yet, even then, they made transaction time columns not quite first-class in that an application can set their values as a side-effect of a transaction only.

in addition, they establish special forms for which the semantics is to effect an operation with implicit constraints on the columns which reflect valid and transaction time and they modify other operation semantics - for example referential integrity constraints to automatically incorporate the values present  in these columns.
if nothing else, the thirty years of effort indicates that this bit of asymmetry in the relational model is well tolerated as it contributes to correct applications.

with this in mind, consider the nature of temporal rdf data.
rdf decimates everything and, at least in principle, represents assertions in a four-dimensionsal space. graph semantics make the space anisotropic, but  that is artifactual.
on the basis of this quad-space, rdf models introduce additional dimensionality (analogous to relational columns) in the way they handle predicates: each is its own dimension.
given which, the issue can be expressed as, does a mechanism enforce orthogonality among properties which are to serve respective time dimensions and between them and other property dimensions?
the orthogonality which sql-2011 enforces with respect to time dimensions - different referential integrity and modification semantics, contributes to application correctness.
if you implement deletion by marking, you subvert this quite useful distinction and handle transaction time as a parallel dimension to any other dimension . including valid-time dimensions.

that is why i earlier asked, what happens to the containment assertions.
the approach which marks the entity, but deletes the containment assertions inflicts (at least from some perspectives) as much of an integrity violation as were it to do the opposite.
i have worked with an application which effected the marking by defining a shadow class hierarchy and changing the class of respective to-be-deleted entities.
as the access operators were all class driven, that was cool, but the cognitive and processing load of dealing with content which was, from a duck-typing perspective, just an increasing amount of debris, was not productivity-enhancing.

if a store permits to represent transaction time only through the presence - or absence, of an assertion, that is, it can represent just one point in that dimension through insertion and deletion, then that is the method to employ rather than to emulate that dimension in valid-time space.
yes, it is a computer and layers recurse indefinitely, but each will either contribute to or encumber the quality, which makes it difficult to recommend a method which treats a transaction time dimension as if it concerned matters of truth rather than existence.

**Comment by no-reply** [comment]
I _think_ I understand all of what you're saying, at least superficially, but I'm not seeing the practical implications respecting the recommendation against the deletion approach employed here. I think you may be interpreting "marking" with some jargon meaning which is not intended or manifest in the implementation. 

Here is the lifecycle of an ldp:Resource as implemented:
- Prior to creation, the resource is `404 Not Found`.
- The resource is created by a POST to a container or a PUT directly to the target URI. At this time:
  - In the backend some triples are added to a named graph (`#metagraph`) tracking server-internal properties. Currently, this includes an `rdf:type` triple giving the LDP interaction model for the resource and a `dcterms:modified` triple with a `Last-Modified` date.
  - If the Resource is an RDFSource, a second named graph is populated from the POST/PUT body. This graph is understood as representing the current state of the RDFSource itself, in the sense described in LDP.
  - If the Resource is a NonRDFSource, a file derived from the POST/PUT body is written to disk.
  - If the Resource was posted to a Container, containment and membership triples appropriate to the Container type are added to _other_ Resources as required by LDP.
  - Barring an error state, the Resource responds `201 Created`
- The Resource is retrieved with GET requests:
  - The Resource responds `200 OK`, giving the current state (graph or file) in the body.
- The Resource is updated by PUT or PATCH requests:
  - The graph or file is updated as requested.
  - The `dcterms:modified` triple is updated.
  - The Resource responds `200 OK`.
- The Resource is destroyed by a DELETE request:
  - **The graph or file representing the current external state is emptied/deleted**.
  - Containment/membership triples are removed from other Resources as required by LDP.
  - A `prov:invalidatedAtTime` triple is added to `#metagraph` giving the time of the deletion.
  - The Resource responds `204 No Content`.
    - The Resource is retrieved with GET requests, and gives `410 Gone`.

In my understanding, all of the above interactions are oriented squarely in transaction time. Depending on the behavior and capabilities of the backend, you may or may not be able to retrieve prior states of the Graph, allowing for (transaction) rollback.

In practical terms, it's not clear to me: (a) where you see the valid-time dimension entering the picture; (b) at what point the above approach goes wrong re: bitemporality; or (c) what an alternative proposal might be. 

There's a need, derived from HTTP and LDP, to be able to understand a resource as existing (and having a specific LDP interaction model), or as having existed but now being gone, independent of the presence of any content in its representation. That's the role that the statements in `#metagraph` fill.

**Comment by lisp** [comment]
i had misinterpreted your reply of six days ago

> We are currently marking resources as "deleted" (as a result of DELETE requests; and leading to Gone responses) by adding a triple <> rdf:type owl:Nothing to the resource's #metagraph. This is probably a bit ontologically heavy.

to have implied that the mark was the only indication of deletion.

**Comment by lisp** [comment]
> In practical terms, it's not clear to me: (a) where you see the valid-time dimension entering the picture; (b) at what point the above approach goes wrong re: bitemporality; or (c) what an alternative proposal might be.

your meta-graph content is a meta-level model of the state of your ldp-model in which the temporal intervals emulate transaction time. absent native support for transactional time, there is no choice. still:
- it is not clear, what happens, if some request reloads the known-but-deleted resource. if the ldp protocol eventually proscribed that, the problem does not arise, but, in general existence is not directly indicated.
- if i understand the ldp interaction model correctly, the asserted prov:invalidatedAtTime is as much a prov:generatedAtTime assertion for the tombstone. the emulation would be improved if it were more complete. to this end, it would be better to always assert the start time for the created resources as well, just as (effectively) for the tombstone.
